name: R-CMD-check
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual")'
          args: 'c("--no-manual","--ignore-vignettes")'
